### ISSUE TITLE
Rename to Fira Neue

### ISSUE THREAD

**Issue by indolering** [carrois/Fira#16]
I think it might be better to rename this as Fira Neue:

* Changes to spacing and existing characters should be considered breaking, but we don't have a way to pin the version down in Google Fonts.
* Mozilla won't update the repo to point here.
* It's going to be equally difficult to update all of the sites currently linking to the old repo.

**Comment by carrois** [comment]
Hi Zach.
We understand your approach but things are a bit more difficult from our perspective.
> Changes to spacing and existing characters should be considered breaking, but we don't have a way to pin the version down in Google Fonts.
It’s not only changes to the spacing etc. – it’s also proper bug fixing and developing the typeface further, supporting more languages and so on.
We don’t see any reason to stay with the „old“ versions of Fira for anybody. It would be great if you could simply update the fonts on googlefonts and link to the new repo. There might be linespacing issues compared to very old versions, yes. But the new settings solve different issues. If developers adapt their linespacing once, it will be compatible with every new update.
> Fira Neue:
> 

The point is that the past-Mozilla versions are not new. They are simply better, reworked versions – in best Open Source manner if you like. So the name is misleading. The other point is that there will be a real „Fira Neue“ (to stay with your working title) soon. With massive language support (Arabic, Hebrew, Devanagari, Thai, Georgian) and manual True Type hinting. There will be a new repo for that version.
> Mozilla won't update the repo to point here.

Well, they are responsible for their repo. We cannot and don’t want to moderate it or take any further influence. If they won’t answer requests and googlefonts links to the new repo/resp. our website, it’s only a matter of time people switch repos. There are already issues where people wonder what’s going on. 

We are not happy about how the whole project was dropped, you can imagine. So we decided to push it forward on ourselves and we will not rename it, at least not the revised “original”. 

Best, C’
