### ISSUE TITLE
Issues with new ligatures

### ISSUE THREAD

**Issue by BonnEconLab** [carrois/Fira#3]
(1) The new ligatures (ff, ffi, ffj, ft, …) are categorized as discretionary ligatures instead of standard ligatures.
(2) More severly, behavior of the ffi ligature in the roman fonts is a bit weird: When selecting “Historical and Discretionary Ligatures” in Word (2016 for Mac), the ffi ligature is applied correctly. However, when selecting “All Ligatures,” it is not. Surprisingly, the ffi ligature works flawlessly in the italics version. In contrast to ffi, ff and ffj work just fine in both the italics and the roman versions.
This behavior is not Word-related because the missing ffi ligature can also be observed when typesetting text with XeLaTeX and the fontspec package.

Screenshots:
<img width="1639" alt="Word 2016 Mac" src="https://cloud.githubusercontent.com/assets/6792766/19501921/a4c6022a-95a9-11e6-900f-196e6fa75ac3.png">
<img width="996" alt="XeLaTeX" src="https://cloud.githubusercontent.com/assets/6792766/19501923/a50576ee-95a9-11e6-9674-f0de36dee93d.png">

**Comment by carrois** [comment]
Hi. Thank you, we noticed that as well while dealing with issue #2.

dlig and lig feature simply have the wrong order in the Roman source file, no need to investigate further. That’s why Italics works fine. Will be solved with the next release. But let’s collect issues until next week because 92 files have to be produced...

**Comment by carrois** [comment]
Should be working in the new version. Can you confirm? Thanks.

**Comment by BonnEconLab** [comment]
Dear carrois (et al.),

Thanks a lot for fixing this so quickly! I can confirm that the new ligatures are now accessible both in Microsoft Word (2016, Windows as well as Mac) and in XeLaTeX—albeit as “discrete ligatures” (dlig) instead of “standard ligatures” (lig), see the discussion at https://github.com/carrois/Fira/issues/2.

Also many thanks in general for the huge amount of labor that went—and still goes—into designing and extending this awesome font family!
