### ISSUE TITLE
Please consider providing Unicode 9.0 power symbols

### ISSUE THREAD

**Issue by fitojb** [carrois/Fira#5]
Unicode 9.0 has added (at last) some actually useful symbols, besides the emoji fluff. The ISO/IEC/IEEE power symbols (standby, on, off, etc.), which are pretty useful in e.g. technical documentation and manuals (fitting Fira’s use cases, I’d say), were [proposed](http://www.unicode.org/L2/L2014/14009r-power-symbol.pdf) and [added](http://www.unicode.org/charts/PDF/Unicode-9.0/U90-2300.pdf) to the “Miscellaneous Technical” block at the following code points:

```
POWER SYMBOL         U+23FB  ⏻
POWER ON-OFF SYMBOL  U+23FC  ⏼
POWER ON SYMBOL      U+23FD  ⏽
HEAVY CIRCLE         U+2B58  ⭘
POWER SLEEP SYMBOL   U+23FE  ⏾
```

**Comment by carrois** [comment]
Good idea. We’ll include them in the next update.

**Comment by fitojb** [comment]
I can see this is fixed in the new FiraGO. Thanks a lot!!
