### ISSUE TITLE
Missing stylistic set 4 in FiraSans Regular

### ISSUE THREAD

**Issue by Boa2** [carrois/Fira#7]
In FiraSans Regular the OpenType stylistic set 4 is missing. 

-Andrea

**Comment by carrois** [comment]
Hi Andrea. Sorry for replying late.
Which version do you use? I had a look at 4203 and it seems to work...

**Comment by Boa2** [comment]
Hi carrois, the version that you launched by the end of February has the stylistic set included. So everything is fine now. I've mentioned this here: https://github.com/carrois/Fira/issues/8 , but forgot to close this issue - sorry.

Thanks for this great font family!
-Andrea
