### ISSUE TITLE
Converting to webfonts using subset for smaller filesizes 

### ISSUE THREAD

**Issue by Boa2** [carrois/Fira#8]
I would like to use FiraSans fonts on a website. The webfonts in the download are quite heavy. Therefore I would like to convert the fonts using a subset only. 

As far as I understand the license I have to rename all fontnames on OS level and inside a programm like FontForge. As far as FontForge is concerned: Would it be sufficient to alter all font names inside the font info window -> PS Names and -> TTF Names? Or is there any other place where I need to change the font names?

Thanks, 
Andrea

**Comment by carrois** [comment]
Hi.

We will provide Latin subsets by the end of next week anyway. If you can wait so long ... ;-)

on the way _ please excuse typos and briefness _ ralph

**Comment by Boa2** [comment]
That is great news.
Will the OpenType Stylistic Sets be part of this subset? I would like to use a least set 4.
-Andrea

**Comment by carrois** [comment]
I'll keep that in mind ;-)


on the way _ please excuse typos and briefness _ ralph

**Comment by Boa2** [comment]
WOW :-)
-Andrea

**Comment by carrois** [comment]
Hi.

Silent Launch on Github only.

Please finde all weights and widths as Latin subsets here:
https://github.com/carrois/Fira/tree/master/Fira_Sans_web_subset_Latin

WOFF and WOFF2 only.
Size 20-32K per font file
Read more the log file.

Hope that does help.
And please let us know if it works on your side, too.
_r


Carrois’
Simplonstr. 54 _ 10245 Berlin _ Germany _ www.carrois.com
Ralph du Carrois _ T 0049 30 920 389 66 _ M 0049 179 20 60 768
–

**Comment by Boa2** [comment]
Thanks for the webfont subsets. They are working incl. Stylistic Set 4 :-)
-Andrea

**Comment by kevquirk** [comment]
> 
> Hi. Silent Launch on Github only. Please finde all weights and widths as Latin subsets here: https://github.com/carrois/Fira/tree/master/Fira_Sans_web_subset_Latin WOFF and WOFF2 only. Size 20-32K per font file Read more the log file. Hope that does help. And please let us know if it works on your side, too. _r Carrois’ Simplonstr. 54 _ 10245 Berlin _ Germany _ [www.carrois.com](http://www.carrois.com) Ralph du Carrois _ T 0049 30 920 389 66 _ M 0049 179 20 60 768 –

This repo seems to have been deleted. Is there a plan to bring these back in this project? Fira is a beautiful font, but it's so heavy.

Thanks.
